# Generated by Django 3.2 on 2021-04-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessionapp', '0002_auto_20210428_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(),
        ),
    ]
