# Generated by Django 3.2 on 2021-04-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True)),
                ('answer1', models.TextField(null=True)),
                ('answer2', models.TextField(null=True)),
                ('answer3', models.TextField(null=True)),
                ('answer4', models.TextField(null=True)),
            ],
        ),
    ]
